package it.unitn.ds1.loggers;

public enum LogType {
    UPDATE,
    READ_REQ,
    READ_DONE,
    UPDATE_REQ,
    FLUSH,

    // crashes
    CLIENT_DETECTS_COHORT_CRASH,
    COHORT_DETECTS_COHORT_CRASH,

    // leader election
    LEADER_ELECTION_START,
    LEADER_FOUND,
    COHORT_RECEIVED_READ_REQUEST_DURING_ELECTION,
    COHORT_RECEIVED_UPDATE_REQUEST_DURING_ELECTION
}
